# Generated by Django 2.1.1 on 2019-06-20 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletes', models.ManyToManyField(blank=True, to='metcons.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='GymOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaches', models.ManyToManyField(blank=True, to='metcons.Coach')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='is_athlete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_gym_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile_privacy',
            field=models.CharField(blank=True, choices=[('Y', 'Private'), ('N', 'Public')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workout_default_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', help_text='This is the default gender that workouts you create will be tagged for. Can be changed on workout creation.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workout_default_privacy',
            field=models.CharField(blank=True, choices=[('Y', 'Private'), ('N', 'Public')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='classification',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metcons.Classification'),
        ),
        migrations.AddField(
            model_name='gymowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athlete',
            name='gym_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metcons.GymOwner'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
