# Generated by Django 2.1.1 on 2019-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutinstance',
            name='assigned_by_coach_or_gym_owner',
            field=models.BooleanField(default=False),
        ),
    ]
