# Generated by Django 2.1.1 on 2019-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0005_workoutinstance_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutinstance',
            name='datetime_to_unhide',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
