# Generated by Django 2.1.1 on 2019-06-23 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0007_auto_20190623_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutinstance',
            old_name='assigned_by_coach_or_gym_owner',
            new_name='is_assigned_by_coach_or_gym_owner',
        ),
        migrations.AddField(
            model_name='workoutinstance',
            name='assigned_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
