# Generated by Django 2.1.1 on 2019-06-30 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0008_auto_20190623_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_adding_coach', models.BooleanField(default=False)),
                ('is_adding_athlete', models.BooleanField(default=False)),
                ('is_adding_gymowner', models.BooleanField(default=False)),
                ('requestee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
