# Generated by Django 2.1.1 on 2019-07-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0011_auto_20190724_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutinstance',
            name='comment',
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='comment',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
