# Generated by Django 2.1.1 on 2019-07-26 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0012_auto_20190724_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_to_database', models.DateTimeField(auto_now_add=True)),
                ('number_of_times_completed', models.IntegerField(default=0, verbose_name='Times Completed')),
                ('distance', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_reps', models.IntegerField(blank=True, default=1, null=True, verbose_name='Reps')),
                ('comment', models.TextField(blank=True, max_length=4000, null=True)),
                ('pace', models.CharField(blank=True, max_length=100, null=True)),
                ('rest', models.IntegerField(blank=True, default=0, null=True)),
                ('cardio_exercise_number', models.IntegerField(default=1)),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metcons.Movement')),
            ],
        ),
        migrations.CreateModel(
            name='CardioWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_to_database', models.DateTimeField(auto_now_add=True)),
                ('number_of_times_completed', models.IntegerField(default=0, verbose_name='Times Completed')),
                ('cardio_exercises', models.ManyToManyField(blank=True, to='metcons.CardioExercise')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='strength_exercise_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutinstance',
            name='cardio_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metcons.CardioWorkout'),
        ),
    ]
