# Generated by Django 2.1.1 on 2019-07-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0013_auto_20190725_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioexercise',
            name='distance_units',
            field=models.CharField(blank=True, choices=[('m', 'm'), ('ft', 'ft'), ('km', 'km'), ('mi', 'mi')], default='m', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight_units',
            field=models.CharField(blank=True, choices=[('lbs', 'lbs'), ('kgs', 'kgs'), ('%', '%')], default='lbs', max_length=5, null=True),
        ),
    ]
