# Generated by Django 2.1.1 on 2019-09-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0014_auto_20190725_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'get_latest_by': ['date_workout_completed', 'date_created']},
        ),
        migrations.AddField(
            model_name='workoutinstance',
            name='last_time_hidden_date_was_checked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
