# Generated by Django 2.1 on 2019-04-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metcons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(blank=True, choices=[('Upper Body', 'Upper Body'), ('Lower Body', 'Lower Body'), ('Total Body', 'Total Body'), ('Cardio', 'Cardio')], default='Total Body', help_text='Is this movement upper, lower, total body or cardio?', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='classifications',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='metcons.Classification'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='movements',
            field=models.ManyToManyField(blank=True, to='metcons.Movement'),
        ),
    ]
